### ISSUE TITLE
Run tutorials without wandb.ai

### ISSUE THREAD

**Issue by jtls0n** [buenrostrolab/scPrinter#11]
Thank you for the informative new tutorials.

Is it possible to run them without connecting to wandb.ai?

Thank you!

**Comment by jtls0n** [comment]
I'm sorry I must be missing something, but I appreciate your help!

In the PBMC_scATAC_tutorial, it seems that skipping the chunk under the title "Using the cell embeddings for LoRA fintune seq2PRINT models" that starts with import wandb is required to generate pretrain_models.

**Comment by jtls0n** [comment]
I seem to have managed to replace the chunk starting with `import wandb` with this:

`pretrain_models = ['PBMC_Bulk_fold0.pt',
                   'PBMC_Bulk_fold1.pt',
                   'PBMC_Bulk_fold2.pt',
                   'PBMC_Bulk_fold3.pt',
                   'PBMC_Bulk_fold4.pt']`

After I run the chunk to generate the terminal commands to run `seq2print_train`, I fail I the terminal with this error:

`wandb.errors.errors.Error: You must call wandb.init() before wandb.config['data_dir']`

The command used in terminal is this:
`CUDA_VISIBLE_DEVICES=0 seq2print_train --config /scratch/PBMC_scATAC_tutorial//seq2print/configs/PBMC_LoRA_fold0.JSON --temp_dir /scratch/PBMC_scATAC_tutorial//seq2print/temp --model_dir /scratch/PBMC_scATAC_tutorial//seq2print/model --data_dir /scratch/PBMC_scATAC_tutorial//seq2print --project None`

**Comment by ruochiz** [comment]
Could you copy the whole error information please? Including which line of the code triggers the error

**Comment by jtls0n** [comment]
Unfortunately, I can't right now. I saw that you had updated some of the functions and wanted to make sure I wasn't using an outdated version (installed Jan 30th). So I created a new environment with the latest edits. From this, the peak calling function in the scATAC tutorial seems to be broken in a way that I can't track down. The errors with the updated environment are below. I guess I can try to go back and pull from an older commit.

`---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[13], line 1
----> 1 scp.pp.call_peaks(printer=printer,
      2                   frag_file=f'{fragment_file}',
      3                   cell_grouping=[list(printer.obs_names)], # here we call peaks on the cells that are included in the final analyses
      4                   group_names=['all'],
      5                   preset='seq2PRINT')

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/scprinter/preprocessing.py:753, in call_peaks(printer, frag_file, cell_grouping, group_names, iterative_peak_merging, merge_across_groups, peak_width, clean_temp, preset, n_jobs, overwrite, sample_names, **kwargs)
    751 for name in group_names:
    752     peak = os.path.join(printer.file_path, "macs2", f"{name}_peaks.narrowPeak")
--> 753     peak = resize_bed_df(pd.read_csv(peak, sep="\t", header=None), peak_width)
    754     peak_calling[name] = peak
    756 if iterative_peak_merging:

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/pandas/io/parsers/readers.py:948, in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, date_format, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options, dtype_backend)
    935 kwds_defaults = _refine_defaults_read(
    936     dialect,
    937     delimiter,
   (...)
    944     dtype_backend=dtype_backend,
    945 )
    946 kwds.update(kwds_defaults)
--> 948 return _read(filepath_or_buffer, kwds)

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/pandas/io/parsers/readers.py:611, in _read(filepath_or_buffer, kwds)
    608 _validate_names(kwds.get("names", None))
    610 # Create the parser.
--> 611 parser = TextFileReader(filepath_or_buffer, **kwds)
    613 if chunksize or iterator:
    614     return parser

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/pandas/io/parsers/readers.py:1448, in TextFileReader.__init__(self, f, engine, **kwds)
   1445     self.options["has_index_names"] = kwds["has_index_names"]
   1447 self.handles: IOHandles | None = None
-> 1448 self._engine = self._make_engine(f, self.engine)

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/pandas/io/parsers/readers.py:1705, in TextFileReader._make_engine(self, f, engine)
   1703     if "b" not in mode:
   1704         mode += "b"
-> 1705 self.handles = get_handle(
   1706     f,
   1707     mode,
   1708     encoding=self.options.get("encoding", None),
   1709     compression=self.options.get("compression", None),
   1710     memory_map=self.options.get("memory_map", False),
   1711     is_text=is_text,
   1712     errors=self.options.get("encoding_errors", "strict"),
   1713     storage_options=self.options.get("storage_options", None),
   1714 )
   1715 assert self.handles is not None
   1716 f = self.handles.handle

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/pandas/io/common.py:863, in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    858 elif isinstance(handle, str):
    859     # Check whether the filename is to be opened in binary mode.
    860     # Binary mode does not support 'encoding' and 'newline'.
    861     if ioargs.encoding and "b" not in ioargs.mode:
    862         # Encoding
--> 863         handle = open(
    864             handle,
    865             ioargs.mode,
    866             encoding=ioargs.encoding,
    867             errors=errors,
    868             newline="",
    869         )
    870     else:
    871         # Binary mode
    872         handle = open(handle, ioargs.mode)

FileNotFoundError: [Errno 2] No such file or directory: '/scratch//PBMC_scATAC_tutorial//seq2print/PBMC_scATAC_scprinter_supp/macs2/all_peaks.narrowPeak'`

**Comment by jtls0n** [comment]
Ok after going back to the earlier commit, peak calling works again.

Here is the command I ran:

`CUDA_VISIBLE_DEVICES=0 seq2print_train --config PBMC_scATAC_tutorial//seq2print/configs/PBMC_LoRA_fold0.JSON --temp_dir PBMC_scATAC_tutorial//seq2print/temp --model_dir PBMC_scATAC_tutorial//seq2print/model --data_dir PBMC_scATAC_tutorial//seq2print --project None`

Here is the error:

`start a new run!!!
Traceback (most recent call last):
  File "/home/user/miniforge3/envs/scprinter/bin/seq2print_train", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/miniforge3/envs/scprinter/lib/python3.11/site-packages/scprinter/seq/scripts/seq2print_lora_train.py", line 728, in main
    entry(config, wandb_run_name, args.enable_wandb)
  File "/home/user/miniforge3/envs/scprinter/lib/python3.11/site-packages/scprinter/seq/scripts/seq2print_lora_train.py", line 106, in entry
    data_dir = config["data_dir"]
               ~~~~~~^^^^^^^^^^^^
  File "/home/user/miniforge3/envs/scprinter/lib/python3.11/site-packages/wandb/sdk/lib/preinit.py", line 14, in __getitem__
    raise wandb.Error(f"You must call wandb.init() before {self._name}[{key!r}]")
wandb.errors.errors.Error: You must call wandb.init() before wandb.config['data_dir']`

**Comment by ruochiz** [comment]
Thank you for all this information. And about the peak calling error. I'll look into it ASAP. I do get other users reporting the peak calling error, so this is really helpful.

**Comment by ruochiz** [comment]
Hi. I just commit a fix for the training script without wandb.ai

But as you mentioned some error might break the peak calling function, could you try to rerun scp.pp.call_peaks, but this times setting n_jobs=1 for debugging purpose? Thx!

Please copy all the output and error information here, thx!

**Comment by ruochiz** [comment]
OK. I think I know why. it is because some fragments file have comment lines starting with # that breaks some of the code I updated. This should be fixed now.

**Comment by jtls0n** [comment]
I updated to current commit and reran (with/without n_jobs = 1), resulting in the errors below. 

**Without n_jobs=1**
`--------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[8], line 1
----> 1 scp.pp.call_peaks(printer=printer,
      2                   frag_file=f'{fragment_file}',
      3                   cell_grouping=[list(printer.obs_names)], # here we call peaks on the cells that are included in the final analyses
      4                   group_names=['all'],
      5                   #n_jobs=1,
      6                   preset='seq2PRINT')

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/scprinter/preprocessing.py:758, in call_peaks(printer, frag_file, cell_grouping, group_names, iterative_peak_merging, merge_across_groups, peak_width, clean_temp, preset, n_jobs, overwrite, sample_names, **kwargs)
    756 for name in group_names:
    757     peak = os.path.join(printer.file_path, "macs2", f"{name}_peaks.narrowPeak")
--> 758     peak = resize_bed_df(pd.read_csv(peak, sep="\t", header=None, comment="#"), peak_width)
    759     peak_calling[name] = peak
    761 if iterative_peak_merging:

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/pandas/io/parsers/readers.py:948, in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, date_format, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options, dtype_backend)
    935 kwds_defaults = _refine_defaults_read(
    936     dialect,
    937     delimiter,
   (...)
    944     dtype_backend=dtype_backend,
    945 )
    946 kwds.update(kwds_defaults)
--> 948 return _read(filepath_or_buffer, kwds)

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/pandas/io/parsers/readers.py:611, in _read(filepath_or_buffer, kwds)
    608 _validate_names(kwds.get("names", None))
    610 # Create the parser.
--> 611 parser = TextFileReader(filepath_or_buffer, **kwds)
    613 if chunksize or iterator:
    614     return parser

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/pandas/io/parsers/readers.py:1448, in TextFileReader.__init__(self, f, engine, **kwds)
   1445     self.options["has_index_names"] = kwds["has_index_names"]
   1447 self.handles: IOHandles | None = None
-> 1448 self._engine = self._make_engine(f, self.engine)

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/pandas/io/parsers/readers.py:1705, in TextFileReader._make_engine(self, f, engine)
   1703     if "b" not in mode:
   1704         mode += "b"
-> 1705 self.handles = get_handle(
   1706     f,
   1707     mode,
   1708     encoding=self.options.get("encoding", None),
   1709     compression=self.options.get("compression", None),
   1710     memory_map=self.options.get("memory_map", False),
   1711     is_text=is_text,
   1712     errors=self.options.get("encoding_errors", "strict"),
   1713     storage_options=self.options.get("storage_options", None),
   1714 )
   1715 assert self.handles is not None
   1716 f = self.handles.handle

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/pandas/io/common.py:863, in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    858 elif isinstance(handle, str):
    859     # Check whether the filename is to be opened in binary mode.
    860     # Binary mode does not support 'encoding' and 'newline'.
    861     if ioargs.encoding and "b" not in ioargs.mode:
    862         # Encoding
--> 863         handle = open(
    864             handle,
    865             ioargs.mode,
    866             encoding=ioargs.encoding,
    867             errors=errors,
    868             newline="",
    869         )
    870     else:
    871         # Binary mode
    872         handle = open(handle, ioargs.mode)

FileNotFoundError: [Errno 2] No such file or directory: 'PBMC_scATAC_tutorial//seq2print/PBMC_scATAC_scprinter_supp/macs2/all_peaks.narrowPeak'`


**With n_jobs = 1**
---------------------------------------------------------------------------
ParserError                               Traceback (most recent call last)
Cell In[9], line 1
----> 1 scp.pp.call_peaks(printer=printer,
      2                   frag_file=f'{fragment_file}',
      3                   cell_grouping=[list(printer.obs_names)], # here we call peaks on the cells that are included in the final analyses
      4                   group_names=['all'],
      5                   n_jobs=1,
      6                   preset='seq2PRINT')

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/scprinter/preprocessing.py:751, in call_peaks(printer, frag_file, cell_grouping, group_names, iterative_peak_merging, merge_across_groups, peak_width, clean_temp, preset, n_jobs, overwrite, sample_names, **kwargs)
    740         pool.submit(
    741             call_peak_one_group,
    742             printer.file_path,
   (...)
    748             sample_names,
    749         )
    750     else:
--> 751         call_peak_one_group(
    752             printer.file_path, frag_file, grouping, name, preset, clean_temp, sample_names
    753         )
    754 if n_jobs > 1:
    755     pool.shutdown(wait=True)

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/scprinter/preprocessing.py:657, in call_peak_one_group(file_path, frag_file, grouping, name, preset, clean_temp, sample_names)
    653 def call_peak_one_group(
    654     file_path, frag_file, grouping, name, preset, clean_temp=True, sample_names=None
    655 ):
    656     if grouping is not None:
--> 657         create_frag_group(file_path, frag_file, grouping, name, sample_names)
    658     macs2(
    659         (
    660             os.path.join(file_path, f"{name}_filtered_frag.tsv.gz")
   (...)
    666         p_cutoff=0.01 if preset == "seq2PRINT" else None,
    667     )
    668     if clean_temp:

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/scprinter/preprocessing.py:630, in create_frag_group(temp_path, frag_file, cell_grouping, group_name, sample_names)
    628 for frag, sample_name in zip(frag_file, sample_names):
    629     reader = pd.read_csv(frag, sep="\t", header=None, chunksize=100000)
--> 630     for chunk in reader:
    631         chunk_bc = (
    632             chunk[3] if sample_name is None else [sample_name + "_" + xx for xx in chunk[3]]
    633         )
    634         boolean_mask = [xx in bcs for xx in chunk_bc]

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/pandas/io/parsers/readers.py:1668, in TextFileReader.__next__(self)
   1666 def __next__(self) -> DataFrame:
   1667     try:
-> 1668         return self.get_chunk()
   1669     except StopIteration:
   1670         self.close()

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/pandas/io/parsers/readers.py:1777, in TextFileReader.get_chunk(self, size)
   1775         raise StopIteration
   1776     size = min(size, self.nrows - self._currow)
-> 1777 return self.read(nrows=size)

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/pandas/io/parsers/readers.py:1748, in TextFileReader.read(self, nrows)
   1741 nrows = validate_integer("nrows", nrows)
   1742 try:
   1743     # error: "ParserBase" has no attribute "read"
   1744     (
   1745         index,
   1746         columns,
   1747         col_dict,
-> 1748     ) = self._engine.read(  # type: ignore[attr-defined]
   1749         nrows
   1750     )
   1751 except Exception:
   1752     self.close()

File ~/miniforge3/envs/scprinter/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py:234, in CParserWrapper.read(self, nrows)
    232 try:
    233     if self.low_memory:
--> 234         chunks = self._reader.read_low_memory(nrows)
    235         # destructive to chunks
    236         data = _concatenate_chunks(chunks)

File parsers.pyx:855, in pandas._libs.parsers.TextReader.read_low_memory()

File parsers.pyx:904, in pandas._libs.parsers.TextReader._read_rows()

File parsers.pyx:879, in pandas._libs.parsers.TextReader._tokenize_rows()

File parsers.pyx:890, in pandas._libs.parsers.TextReader._check_tokenize_status()

File parsers.pyx:2058, in pandas._libs.parsers.raise_parser_error()

ParserError: Error tokenizing data. C error: Expected 1 fields in line 52, saw 5

**Comment by ruochiz** [comment]
Sorry... I was adding comment="#" to the wrong place. should be fixed now.

**Comment by jtls0n** [comment]
I'm sorry I am still having trouble. The peak calling command is still failing, albeit after much more time than before..

Do you expect the comment option to exist both places?

reader = pd.read_csv(frag, sep="\t", header=None, chunksize=100000, comment="#")
peak = resize_bed_df(pd.read_csv(peak, sep="\t", header=None, comment="#"), peak_width)

**Comment by jtls0n** [comment]
I appreciate your responsiveness, but I am going to have to stop using this until it is fully validated and will close this issue.

Despite being included in the publication, this implementation may still be pre-release.

**Comment by ruochiz** [comment]
Hey. Sorry that you are still running into trouble on this function. This function and many others are implemented after we generated the results for the publication, aiming to contain most of the functions within the package instead of custom scripts + running software in macs2. While that being an ideal case, apparently it can cause bugs, especially on input format that is different from the fragments file we worked on (produced from our share-seq pipeline). 

The bug on this function is probably introduced when I try to let it support multiple 10x fragments files with barcode collision (something we don't have to work with before). I'll throughly test this version and let you know the results.

Again, apologize for any inconvenience, and thx for the being the beta user.

**Comment by ruochiz** [comment]
Hey,

I just double tested on my end that the latest commit should address the bugs. And at least it should reach to a point that it will print out things like 

```
running macs2 with macs2 callpeak --nomodel -t /ewsc/rzhang/250204_scPrinter_tutorial/PBMC_scATAC_tutorial/seq2print/PBMC_scATAC_scprinter_supp/all_filtered_frag.tsv.gz --outdir /ewsc/rzhang/250204_scPrinter_tutorial/PBMC_scATAC_tutorial//seq2print/PBMC_scATAC_scprinter_supp/macs2 -n all -f BEDPE --nolambda --keep-dup all --call-summits --nomodel -B --SPMR --shift 75 --extsize 150 -p 0.01
```
which would help to see if it's an environment setup issue or implementation issue.

**Comment by ruochiz** [comment]
Cool. thanks for confirming that. 

Wandb.ai is a recommended way to track trained models and retrieve them in a automatic way, but u can replace pretrain_models with your local path manually. 

Regarding failed to launch seq2print_train without wandb, I'll look into it now.

**Comment by ruochiz** [comment]
I have add a patch for non wandb manage seq2print_train. The previous error was triggered for missing wandb.run_name which leads to bad file save name. It is now replaced with a random string instead. I can finish training successfully on my side.

**Comment by yuanlizhanshi** [comment]
> Cool. thanks for confirming that.
> 
> Wandb.ai is a recommended way to track trained models and retrieve them in a automatic way, but u can replace pretrain_models with your local path manually.
> 
> Regarding failed to launch seq2print_train without wandb, I'll look into it now.

Hello,

I recently attempted to run seq2print on our HPC cluster, but unfortunately, the HPC cannot access wandb due to the lack of internet connectivity on the compute nodes. However, when I disable wandb by removing the --wandb option, I encounter the following error:

`
seq2print_train --config ATAC_new/configs/ATAC_A5_fold0.JSON --temp_dir /fsa/home/wgw_kongyh/data/scprinter/ATAC_new/temp --model_dir /fsa/home/wgw_kongyh/data/scprinter/ATAC_new/model --data_dir /fsa/home/wgw_kongyh/data/scprinter/ATAC_new
`
The error message is:

`
RuntimeError: [enforce fail at inline_container.cc:642] . invalid file name: /fsa/home/wgw_kongyh/data/scprinter/ATAC_new/temp/

`

This issue might be occurring because, when wandb is disabled, the temporary file names cannot be generated properly during each training epoch.

I would appreciate any insights or suggestions for resolving this.

**Comment by ruochiz** [comment]
Hi. I think the commit 1 hr ago should fix that. As mentioned, I now add a random string + file name when wandb is disabled.

**Comment by jtls0n** [comment]
I was still struggling with some issues after updating, but I think there may be an error in the sc PBMC tutorial where two chunks are showing as text rather than code.

After formatting those, I seem to be training ok with wandb_project=None

**Comment by yuanlizhanshi** [comment]
> Hi. I think the commit 1 hr ago should fix that. As mentioned, I now add a random string + file name when wandb is disabled.

That worked for me, thank you very much

**Comment by ruochiz** [comment]
> I was still struggling with some issues after updating, but I think there may be an error in the sc PBMC tutorial where two chunks are showing as text rather than code.
> 
> After formatting those, I seem to be training ok with wandb_project=None

Ah yes. The tutorial included in this repo and documentation website are up to date. The ones in the PRINT repo have those errors, will update soon.

**Comment by alifarhat40** [comment]
Hi @ruochiz ,

I recently pulled from github and am running into the following error when running seq2print_train:

`
nohup: ignoring input
Traceback (most recent call last):
  File "/home/ali/anaconda3/envs/scprinter/bin/seq2print_train", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/alif/anaconda3/envs/scprinter/lib/python3.11/site-packages/scprinter/seq/scripts/seq2print_lora_train.py", line 715, in main
    wandb.init(
    ^^^^^
UnboundLocalError: cannot access local variable 'wandb' where it is not associated with a value
`
