### ISSUE TITLE
scp.pp.call_peaks() raises FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jayluo2** [buenrostrolab/scPrinter#12]
Attempt to call MACS peaks with the below command (scPrinter version ```1.0.0a```) with `scp.genome.mm10` as in this [tutorial](https://ruochiz.com/scprinter_doc/tutorials/PBMC_scATAC_tutorial.html#Peak-calling):

```
scp.pp.call_peaks(printer=printer,
                  frag_file=fragment_paths_l,
                  cell_grouping=valid_barcodes_l, 
                  group_names=sample_names_bc,
                  preset='seq2PRINT',
                  overwrite=False
                  )
```

where ```valid_barcodes_l``` is a list of file paths to text files containing valid barcodes per sample, and ```frag_file``` is a list of the corresponding sample fragments file paths.

raises a FileNotFoundError:

`FileNotFoundError: [Errno 2] No such file or directory: ‘/path/to/outputs/macs2/all_peaks.narrowPeak’
`

The printer object has attributes

```
AnnData object with n_obs x n_vars = 5174 x 0 backed at ‘/path/to/scPrinter.h5ad'
    obs: 'sample', 'n_fragment', 'frac_dup', 'frac_mito', 'frag_path', 'frag_sample_name', 'tsse'
    uns: 'insertion', 'gff_db', 'genome', 'reference_sequences', 'bias_bw', 'binding score', 'unique_string', 'bias_path', 'footprints'
    obsm: 'insertion_chr11', 'insertion_chrX', 'insertion_chr16', 'insertion_chr8', 'insertion_chr14', 'insertion_chr18', 'insertion_chr10', 'insertion_chr13', 'insertion_chr4', 'insertion_chr12', 'insertion_chr6', 'insertion_chr2', 'insertion_chr1', 'insertion_chr17', 'insertion_chrY', 'insertion_chr5', 'insertion_chr19', 'insertion_chr3', 'insertion_chr9', 'insertion_chr15', 'insertion_chr7'
```

**Comment by ruochiz** [comment]
the issue should be fixed with the latest commit

**Comment by Umaarasu** [comment]
@ruochiz I installed the package 2 days ago and I am still getting a simialr [error]( https://github.com/buenrostrolab/scPrinter/issues/14). How to proceed?
